# Generated by Django 2.2.13 on 2021-01-16 14:57
from django.db import migrations
from django.db import models

import apps.homepage.upload


class Migration(migrations.Migration):

    dependencies = [("homepage", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="modelimage",
            field=models.ImageField(
                upload_to=apps.homepage.upload.UploadToPath("post_images")
            ),
        )
    ]
