# Generated by Django 2.2.13 on 2021-01-16 16:41
import imagefield.fields
from django.db import migrations
from django.db import models

import apps.homepage.upload


class Migration(migrations.Migration):

    dependencies = [("homepage", "0002_auto_20210116_0857")]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="modelimage_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="postimage",
            name="modelimage_ppoi",
            field=imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
        ),
        migrations.AddField(
            model_name="postimage",
            name="modelimage_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="modelimage",
            field=imagefield.fields.ImageField(
                height_field="modelimage_height",
                upload_to=apps.homepage.upload.UploadToPath("post_images"),
                width_field="modelimage_width",
            ),
        ),
    ]
